version: '3.7'
services:
  kafka-connect-mqtt:
    build: ./build
    hostname: ${REST_ADVERTISED_HOST_NAME:-kafka-connect-mqtt}
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${BROKER_HOSTNAME:?The hostname of the Kafka broker must be set to BROKER_HOSTNAME.}:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: ${REST_ADVERTISED_HOST_NAME:-kafka-connect-mqtt}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: ${GROUP_ID:-kafka-connect-mqtt}
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/usr/share/java/stream-reactor
    ports:
      - "${REST_PORT:-8083}:8083"
