version: '3.7'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
    volumes:
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    init: true
    restart: always
volumes:
  mosquitto-data:
  mosquitto-log:
