version: '3.7'
services:
  kafka-connect:
    image: harbor.vcloud.nii.ac.jp/sinetstream/kafka-connect:0.1.0
    hostname: ${REST_ADVERTISED_HOST_NAME:-kafka-connect}
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${BROKER_HOSTNAME}:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: ${REST_ADVERTISED_HOST_NAME:-kafka-connect}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: ${GROUP_ID:-kafka-connect}
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.converters.ByteArrayConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    ports:
      - "${REST_PORT:-8083}:8083"
