version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    - "9300:9300"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  esdata:
    driver: local
