version: '3.7'
services:
  picamera:
    image: harbor.vcloud.nii.ac.jp/sinetstream/sample/sensor-picamera
    privileged: true
    init: true
    devices:
    - /dev/vchiq:/dev/vchiq
    restart: on-failure:5
    env_file: .env