env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
overrides: []
parserOptions:
  project: ./tsconfig.eslint.json
rules:
  "import/no-extraneous-dependencies":
    - error
    - devDependencies: true
      optionalDependencies: false
  "import/prefer-default-export": "off"
