apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[$KAFKA_TOPIC-]YYYYMMDD"
    url: $ES_URL
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.10.0
    version: 1
    isDefault: true
